/**
 * Session handler — orchestrates a single realtime voice conversation.
 *
 * ┌─────────────┐   Socket.IO (JSON events)   ┌────────────────┐
 * │   Browser   │ ◄──────────────────────────► │  This server   │
 * └─────────────┘                              └───────┬────────┘
 *                                                      │  WebSocket (JSON events)
 *                                               ┌──────▼────────┐
 *                                               │  OpenAI       │
 *                                               │  Realtime API │
 *                                               └───────────────┘
 *
 * ── §2 Conversation History ───────────────────────────────────────────────
 *
 *   Layer 1 — Verbatim recent turns (HISTORY_INJECTION_TURNS)
 *     Injected as conversation.item.create after session.updated.
 *     session.updated is forwarded to the client only AFTER all items are sent.
 *
 *   Layer 2 — Rolling summary in system prompt
 *     Cached summary of previous sessions embedded in session.update.instructions.
 *     Regenerated by gpt-4o-mini after every session ends.
 *
 * ── §3 Tool Injection & Dynamic Prompts ──────────────────────────────────
 *
 * ── §4 Structured Output — per-turn feedback ─────────────────────────────
 *
 *   After every normal AI response.done, the server sends a second silent
 *   response.create (text-only, JSON instructions — no tool_choice).
 *   The AI returns a raw JSON object with grammar_errors[], fluency_score,
 *   and a tip via response.text.done.
 *   The server parses it and emits a "turn_feedback" custom event to the
 *   client, which renders a feedback card below the AI bubble.
 *   All events during the feedback round-trip are suppressed from the client.
 *
 *   §3a — Dynamic prompt injection
 *     User profile (name, level, etc.) is fetched from Redis at session start
 *     and embedded in session.update.instructions alongside the history summary.
 *
 *   §3b — Function calling
 *     The `get_user_profile` tool is registered in session.update.  When the
 *     AI calls it, the server executes it locally, submits the result, and
 *     calls response.create to continue the conversation.
 *
 * ── Tool call event flow ──────────────────────────────────────────────────
 *
 *   Phase 1 — AI calls a function (no audio output)
 *     OpenAI → response.created
 *     OpenAI → response.output_item.added  (item.type: "function_call")
 *     OpenAI → response.function_call_arguments.delta  × N
 *     OpenAI → response.function_call_arguments.done
 *     OpenAI → response.done   (suppressed from client — keeps bubble alive)
 *
 *   Phase 2 — Server executes and continues
 *     Server → conversation.item.create  (function_call_output)
 *     Server → response.create
 *     Server → tool_call_complete  (custom event: client clears indicator)
 *
 *   Phase 3 — AI speaks with the result
 *     OpenAI → response.created   (suppressed from client — reuse existing bubble)
 *     OpenAI → response.audio.delta × N → response.audio.done
 *     OpenAI → response.audio_transcript.done
 *     OpenAI → response.done   (forwarded — client finalises bubble)
 *
 * ── Ordering guarantee ────────────────────────────────────────────────────
 *
 *   connect → pre-fetch (profile + summary + history) resolves
 *           → session.update sent (with enriched instructions)
 *           → session.updated received → turns injected
 *           → session.updated forwarded to client
 *           → history_injected event → autoStartRecording fires
 *           → user speaks (AI has full context)
 */

import fs from "fs";
import path from "path";
import WebSocket from "ws";
import { Socket } from "socket.io";
import { OPENAI_REALTIME_URL, HISTORY_INJECTION_TURNS, DATA_DIR } from "./constants";
import { sessionTimestamp } from "./pcm-utils";
import { TranscriptManager } from "./transcript-manager";
import { AudioRecorder } from "./audio-recorder";
import { SessionStore } from "./session-store";
import { HistoryStore, type ConversationTurn } from "./history-store";
import { getCachedSummary, generateAndCacheSummary } from "./session-summarizer";
import { UserProfileStore, type UserProfile } from "./user-profile-store";
import { TOOL_DEFINITIONS, executeTool } from "./tool-handler";
import { uploadRecording } from "./storage-service";

// ── System prompt builder ─────────────────────────────────────────────────────

/**
 * Builds the `instructions` string for session.update.
 *
 * Combines the base prompt, profile fields (§3a), and rolling summary (§2).
 */
function buildInstructions(
  language: string,
  summary:  string | null,
  profile:  UserProfile,
): string {
  const parts: string[] = [
    `You are a language learning conversation partner. Your only purpose is to help the user practice speaking ${language}.`,
    `Conduct every part of the conversation in ${language}.`,
    `Keep your responses short and natural — like a real conversation between two people.`,
    `Stay strictly focused on language learning: have conversations, gently correct grammar and vocabulary mistakes inline, and help the user improve their ${language}.`,
    `If the user says anything unrelated to language practice (for example: general knowledge questions, news, coding help, or any non-language topic), briefly acknowledge it and redirect them back to practicing ${language}. Do not answer off-topic questions.`,
  ];

  // §3a — inject profile fields so the AI has immediate context without a tool call
  if (profile.name)           parts.push(`The user's name is ${profile.name}.`);
  if (profile.nativeLanguage) parts.push(`Their native language is ${profile.nativeLanguage}.`);
  if (profile.level)          parts.push(`Their ${language} level is approximately ${profile.level}.`);
  if (profile.interests)      parts.push(`They enjoy talking about: ${profile.interests}.`);
  if (profile.goals)          parts.push(`Their learning goal: ${profile.goals}.`);

  let instructions = parts.join(" ");

  // §2 — append rolling summary from previous sessions
  if (summary) instructions += `\n\nContext from previous sessions: ${summary}`;

  return instructions;
}

// ── Session handler ───────────────────────────────────────────────────────────

/**
 * Creates and manages all resources for one client session.
 * Called once per Socket.IO `connection` event.
 */
export function handleRealtimeSession(socket: Socket): void {

  // ── Session metadata ────────────────────────────────────────────────────
  const language  = (socket.handshake.query["language"] as string) || "English";
  const userId    = (socket.handshake.query["userId"]   as string) || socket.id;
  const sessionTs = sessionTimestamp();
  const shortId   = socket.id.slice(0, 8);
  const sessionId = `${sessionTs}_${shortId}`;

  console.log(`\n[session] ── NEW SESSION ──────────────────────────`);
  console.log(`[session]   socket    : ${socket.id}`);
  console.log(`[session]   userId    : ${userId}`);
  console.log(`[session]   language  : ${language}`);
  console.log(`[session]   sessionId : ${sessionId}`);

  // ── Per-session services ────────────────────────────────────────────────
  const transcript   = new TranscriptManager();
  const recorder     = new AudioRecorder(sessionTs, shortId);
  const sessionStore = new SessionStore(sessionId);
  const historyStore = new HistoryStore(userId, sessionId);

  // ── §2 / §3 state ───────────────────────────────────────────────────────

  /** Turns to inject after session.updated (set by pre-fetch). */
  let pendingHistoryTurns: ConversationTurn[] = [];

  /** Turns completed in THIS session (used for end-of-session summary). */
  const sessionTurns: Array<{ role: "user" | "assistant"; text: string }> = [];

  /** Active function call being accumulated. Null when no call is in flight. */
  let activeFunctionCall: {
    callId:     string;
    name:       string;
    argsBuffer: string;
  } | null = null;

  /**
   * When true, the next `response.created` event is suppressed from being
   * forwarded to the client.  Set after a tool call so the AI's continuation
   * response reuses the existing bubble rather than creating a new one.
   * Also set before the silent feedback response.create so no new bubble opens.
   */
  let suppressNextResponseCreated = false;

  /**
   * Set to true while waiting for the AI's structured JSON feedback response.
   * All OpenAI events during this round-trip are suppressed from the client.
   */
  let awaitingFeedback = false;

  /** Accumulates response.text.delta chunks during the feedback round-trip. */
  let feedbackTextBuffer = "";

  // ── Pre-fetch: profile + summary + history (all in parallel) ────────────
  // Starts immediately when the socket connects, overlapping with the OpenAI
  // WS connection + session.created handshake.
  const prefetchPromise = Promise.all([
    getCachedSummary(userId),
    historyStore.getRecentTurns(HISTORY_INJECTION_TURNS),
    new UserProfileStore(userId).get(),
  ]).catch((err: unknown): [null, ConversationTurn[], UserProfile] => {
    console.error("[session] pre-fetch failed:", err);
    return [null, [], {}];
  });

  // ── Connect to OpenAI Realtime API ──────────────────────────────────────
  const openaiWs = new WebSocket(OPENAI_REALTIME_URL, {
    headers: {
      Authorization: `Bearer ${process.env.OPENAI_API_KEY}`,
      "OpenAI-Beta": "realtime=v1",
    },
  });

  // ════════════════════════════════════════════════════════════════════════
  // OpenAI → Client  (receive events from OpenAI, forward to browser)
  // ════════════════════════════════════════════════════════════════════════

  openaiWs.on("open", () => {
    console.log("[session] OpenAI WebSocket opened");
  });

  openaiWs.on("message", (raw: WebSocket.RawData) => {
    let event: Record<string, unknown>;
    try {
      event = JSON.parse(raw.toString()) as Record<string, unknown>;
    } catch {
      console.warn("[session] non-JSON frame from OpenAI — ignoring");
      return;
    }

    const t = event.type as string;

    if (t !== "response.audio.delta" && t !== "response.audio_transcript.delta") {
      console.log(`[openai →] ${t}`);
    }

    // ── session.created — configure session after pre-fetch resolves ─────
    if (t === "session.created") {
      transcript.init(sessionTs, shortId, language);
      sessionStore.create(userId, language).catch((err: unknown) =>
        console.error("[session-store] create failed:", err),
      );

      // Send session.update AFTER pre-fetch so the instructions include both
      // the user profile (§3a) and the history summary (§2).
      prefetchPromise.then(([summary, turns, profile]) => {
        pendingHistoryTurns = turns;

        const instructions = buildInstructions(language, summary, profile);
        if (summary)            console.log("[history] summary injected into instructions");
        if (profile.name)       console.log(`[profile] injected: name=${profile.name}`);
        if (profile.level)      console.log(`[profile] injected: level=${profile.level}`);

        console.log("[session] sending session.update");
        openaiWs.send(
          JSON.stringify({
            type: "session.update",
            session: {
              modalities:    ["text", "audio"],
              instructions,
              voice:         "alloy",
              input_audio_format:  "pcm16",
              output_audio_format: "pcm16",
              input_audio_transcription: { model: "gpt-4o-mini-transcribe" },
              turn_detection: null,
              // §3b — register interactive tools (feedback uses plain JSON text, no tool needed)
              tools:       [...TOOL_DEFINITIONS],
              tool_choice: "auto",
            },
          }),
        );
      });

      socket.emit("message", event);
      return;
    }

    // ── session.updated — inject history, then notify client ─────────────
    // Guaranteed ordering: session.updated only fires after session.update was
    // sent, which only happens after prefetchPromise resolved (pendingHistoryTurns set).
    if (t === "session.updated") {
      const count = pendingHistoryTurns.length;

      if (count > 0) {
        console.log(`[history] injecting ${count} verbatim turn(s)`);
        for (const turn of pendingHistoryTurns) {
          openaiWs.send(
            JSON.stringify({
              type: "conversation.item.create",
              item: {
                type: "message",
                role: turn.role,
                content: [{
                  type: turn.role === "user" ? "input_text" : "text",
                  text: turn.text,
                }],
              },
            }),
          );
        }
      } else {
        console.log("[history] no prior turns to inject");
      }

      socket.emit("message", event);
      socket.emit("message", { type: "history_injected", count });
      pendingHistoryTurns = [];
      return;
    }

    // ── §3b: Track function calls ────────────────────────────────────────

    if (t === "response.output_item.added") {
      const item = event["item"] as Record<string, unknown> | undefined;
      if (item?.["type"] === "function_call") {
        activeFunctionCall = {
          callId:     item["call_id"]  as string,
          name:       item["name"]     as string,
          argsBuffer: (item["arguments"] as string) ?? "",
        };
        console.log(`[tools] function_call: ${activeFunctionCall.name}  call_id=${activeFunctionCall.callId}`);
      }
    }

    if (t === "response.function_call_arguments.delta" && activeFunctionCall) {
      activeFunctionCall.argsBuffer += (event["delta"] as string) ?? "";
    }

    if (t === "response.function_call_arguments.done" && activeFunctionCall) {
      // Use the definitive args string from .done (overrides accumulated deltas)
      activeFunctionCall.argsBuffer = (event["arguments"] as string) ?? activeFunctionCall.argsBuffer;
    }

    // ── User transcription ───────────────────────────────────────────────
    if (
      t === "conversation.item.input_audio_transcription.completed" &&
      typeof event["transcript"] === "string" &&
      event["transcript"].trim()
    ) {
      const text = event["transcript"].trim();
      transcript.appendUser(text);
      historyStore.appendTurn("user", text).catch((err: unknown) =>
        console.error("[history] user turn save failed:", err),
      );
      sessionTurns.push({ role: "user", text });
    }

    // ── AI audio streaming ───────────────────────────────────────────────
    if (t === "response.audio.delta" && typeof event["delta"] === "string") {
      recorder.appendAiChunk(event["delta"]);
    }

    if (t === "response.audio.done") {
      console.log(`[openai →] response.audio.done`);
    }

    // ── AI transcript ────────────────────────────────────────────────────
    if (
      t === "response.audio_transcript.done" &&
      typeof event["transcript"] === "string" &&
      event["transcript"].trim()
    ) {
      const text = event["transcript"].trim();
      transcript.appendAssistant(text);
      historyStore.appendTurn("assistant", text).catch((err: unknown) =>
        console.error("[history] assistant turn save failed:", err),
      );
      sessionTurns.push({ role: "assistant", text });
    }

    // ── §4 Feedback text streaming ────────────────────────────────────────
    // During the feedback round-trip, OpenAI streams a plain JSON string via
    // response.text.delta / response.text.done instead of audio.

    if (t === "response.text.delta" && awaitingFeedback && typeof event["delta"] === "string") {
      feedbackTextBuffer += event["delta"] as string;
    }

    if (t === "response.text.done" && awaitingFeedback) {
      const rawText = (event["text"] as string | undefined) ?? feedbackTextBuffer;
      console.log(`[feedback] text.done: ${rawText.slice(0, 160)}`);

      let feedback: unknown = null;
      try {
        // Strip any accidental markdown fences the model might add
        const clean = rawText.replace(/^```(?:json)?\s*/i, "").replace(/\s*```$/, "").trim();
        feedback = JSON.parse(clean);
      } catch {
        console.warn("[feedback] could not parse feedback JSON — skipping");
      }

      if (feedback) {
        socket.emit("message", { type: "turn_feedback", feedback });
      }
    }

    // ── Determine whether to forward this event to the client ────────────
    //
    // Events suppressed to keep the client's bubble/state intact:
    //
    //   awaitingFeedback (any event):
    //     All events during the silent feedback round-trip are suppressed.
    //     The client never sees the feedback response.create / text streaming.
    //
    //   response.done (function_call phase):
    //     Suppressed so the client stays in 'responding' state while the
    //     server executes the tool and sends response.create.
    //
    //   response.created (tool-continuation phase):
    //     Suppressed so the client doesn't open a second empty bubble.
    //     The existing bubble gets filled when audio/text streams.
    //
    //   response.function_call_arguments.delta:
    //     Suppressed — high-frequency internal event, not useful to the UI.

    const isToolCallDone = t === "response.done" && activeFunctionCall !== null;
    const isContinuation = t === "response.created" && suppressNextResponseCreated;
    const isArgsDelta    = t === "response.function_call_arguments.delta";

    if (isContinuation) suppressNextResponseCreated = false;

    if (!isToolCallDone && !isContinuation && !isArgsDelta && !awaitingFeedback) {
      socket.emit("message", event);
    }

    // ── response.done — normal path, tool call path, or feedback path ────
    if (t === "response.done") {

      if (activeFunctionCall) {
        // ── Interactive tool path (e.g. get_user_profile) ───────────────
        const call = activeFunctionCall;
        activeFunctionCall = null;
        suppressNextResponseCreated = true;

        executeTool(call.name, call.argsBuffer, userId)
          .then((result) => {
            // Emit custom event so client clears the "Calling tool…" indicator
            socket.emit("message", { type: "tool_call_complete", toolName: call.name });

            // Submit the tool result to OpenAI
            openaiWs.send(
              JSON.stringify({
                type: "conversation.item.create",
                item: {
                  type:    "function_call_output",
                  call_id: call.callId,
                  output:  result,
                },
              }),
            );

            // Ask the AI to continue speaking with the result — explicit modalities
            // so OpenAI doesn't inherit the text-only setting from the feedback request.
            openaiWs.send(JSON.stringify({ type: "response.create", response: { modalities: ["text", "audio"] } }));
            console.log(`[tools] ${call.name} result submitted, response.create sent`);
          })
          .catch((err: unknown) => {
            console.error(`[tools] ${call.name} failed:`, err);
            socket.emit("message", { type: "tool_call_complete", toolName: call.name });
            openaiWs.send(
              JSON.stringify({
                type: "conversation.item.create",
                item: { type: "function_call_output", call_id: call.callId, output: JSON.stringify({ error: "Tool failed" }) },
              }),
            );
            openaiWs.send(JSON.stringify({ type: "response.create", response: { modalities: ["text", "audio"] } }));
          });

      } else if (awaitingFeedback) {
        // ── §4 Feedback round-trip complete ─────────────────────────────
        // response.text.done already fired and emitted turn_feedback to client.
        awaitingFeedback   = false;
        feedbackTextBuffer = "";
        console.log("[feedback] round-trip complete");

      } else {
        // ── Normal response path ────────────────────────────────────────
        const filename = recorder.saveAiAudio();

        sessionStore.incrementTurns().catch((err: unknown) =>
          console.error("[session-store] incrementTurns failed:", err),
        );

        if (filename) {
          const aiLocalPath = path.join(DATA_DIR, "recordings", filename);
          // Emit immediately so the audio player appears alongside the feedback card.
          socket.emit("message", { type: "ai_audio_ready", url: `/recordings/${filename}` });
          console.log(`[session] ai_audio_ready → ${filename}`);
          uploadRecording(aiLocalPath, filename)
            .then(() => {
              // Delay deletion so the browser has time to fully load/buffer the file.
              setTimeout(() => {
                fs.unlink(aiLocalPath, (err) => {
                  if (err) console.error(`[cleanup] failed to delete ${filename}:`, err);
                  else console.log(`[cleanup] deleted local file: ${filename}`);
                });
              }, 30_000);
            })
            .catch((err: unknown) => console.error("[minio] ai audio upload failed:", err));
        }

        // §4 — request structured JSON feedback silently (text-only, no tool)
        awaitingFeedback            = true;
        suppressNextResponseCreated = true;

        openaiWs.send(
          JSON.stringify({
            type: "response.create",
            response: {
              modalities:   ["text"],
              instructions:
                "Evaluate the learner's most recent spoken utterance. " +
                "Reply ONLY with valid JSON — no markdown fences, no extra text — in exactly this shape:\n" +
                '{"grammar_errors":[{"original":"...","suggestion":"...","rule":"..."}],"fluency_score":<1-10>,"tip":"..."}\n' +
                "If there are no grammar errors use an empty array [].",
            },
          }),
        );
        console.log("[feedback] requested JSON feedback (text-only response)");
      }
    }
  });

  openaiWs.on("error", (err: Error) => {
    console.error(`[session] OpenAI WebSocket error:`, err.message);
    socket.emit("message", {
      type: "error",
      error: { message: "OpenAI connection error", detail: err.message },
    });
  });

  openaiWs.on("close", () => {
    console.log(`[session] OpenAI WebSocket closed — disconnecting client`);
    socket.disconnect(true);
  });

  // ════════════════════════════════════════════════════════════════════════
  // Client → OpenAI
  // ════════════════════════════════════════════════════════════════════════

  socket.on("message", (data: unknown) => {
    const msg = data as Record<string, unknown>;

    if (msg["type"] === "input_audio_buffer.append" && typeof msg["audio"] === "string") {
      recorder.appendUserChunk(msg["audio"]);
    }

    if (msg["type"] === "done_talking") {
      console.log(
        `[session] done_talking  userChunks=${recorder.userChunkCount}  openaiState=${openaiWs.readyState}`,
      );
      const userFile = recorder.saveUserAudio();
      if (userFile) {
        const userLocalPath = path.join(DATA_DIR, "recordings", userFile);
        uploadRecording(userLocalPath, userFile)
          .then(() => {
            fs.unlink(userLocalPath, (err) => {
              if (err) console.error(`[cleanup] failed to delete ${userFile}:`, err);
              else console.log(`[cleanup] deleted local file after MinIO upload: ${userFile}`);
            });
          })
          .catch((err: unknown) => console.error("[minio] user audio upload failed:", err));
      }

      if (openaiWs.readyState !== WebSocket.OPEN) {
        console.error("[session] OpenAI WS not open — audio saved but no response");
        return;
      }

      openaiWs.send(JSON.stringify({ type: "input_audio_buffer.commit" }));
      // Explicit modalities so OpenAI never inherits text-only from the feedback request.
      openaiWs.send(JSON.stringify({ type: "response.create", response: { modalities: ["text", "audio"] } }));
      console.log("[session] response.create sent");
      return;
    }

    if (openaiWs.readyState !== WebSocket.OPEN) return;
    openaiWs.send(JSON.stringify(data));
  });

  // ── Session teardown ────────────────────────────────────────────────────
  socket.on("disconnect", () => {
    console.log(`[session] client disconnected: ${socket.id}`);

    sessionStore.end().catch((err: unknown) =>
      console.error("[session-store] end failed:", err),
    );

    if (sessionTurns.length >= 2) {
      console.log(`[summarizer] generating summary for ${sessionTurns.length} turns…`);
      generateAndCacheSummary(userId, sessionTurns).catch((err: unknown) =>
        console.error("[summarizer] failed:", err),
      );
    }

    if (openaiWs.readyState !== WebSocket.CLOSED) openaiWs.close();
  });
}
